apiVersion: turing.touchturing.com/v1
kind: Experiment
metadata:
  name: myapp
  namespace: test
spec:
  host: test.com
  image: nginx
  port:
    containerPort: 80
    hostPort: 80
    name: web
  probe:
    path: /
    port: 80
status:
  phase: Running
  subResourcesStatus:
    statestore: true
    statestoreLbService: true
    statestoreService: true
