apiVersion: v1
kind: Pod
metadata:
  name: experiment-controller-manager
  namespace: default
spec:
  containers:
    - name: experiment-controller-manager
      image: new:v2
      volumeMounts:
        - name: kubeconfig
          mountPath: /config
          subPath: config
      env:
        - name: KUBECONFIG
          value: "/config"
      command: ["/c"]
  volumes:
    - name: kubeconfig
      configMap:
        name: kubeconfig
        items:
          - key: config
            path: config
