apiVersion: v1
kind: Pod
metadata:
  name: experiment-controller-manager
  namespace: default
spec:
  containers:
    - name: experiment-controller-manager
      image: new:v2
      env:
        - name: KUBECONFIG
          value: "/root/.kube/config"
      command: ["/c"]
