apiVersion: v1
kind: Pod
metadata:
  name: experiment-controller-manager
  namespace: default
spec:
  containers:
    - name: experiment-controller-manager
      image: harbor.internal.cn:8443/internal/experiment-turing/new:v1
      volumeMounts:
        - name: kubeconfig
          mountPath: /config
          subPath: config
      env:
        - name: KUBECONFIG
          value: "/config"
        - name: REDIS_ADDR
          value: "redis://redis-master:6379"
        - name: REDIS_PASSWORD
          value: "123456"
      command: ["/c"]
  volumes:
    - name: kubeconfig
      configMap:
        name: kubeconfig
        items:
          - key: config
            path: config
